spring:
  application:
    name: host-app
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}
      #      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}
      #     uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}.mongodb.net/${MONGO_DB}
      database: ${MONGO_DB}
      username: ""
      password: ""
  cloud:
    kubernetes:
      secrets:
        name: db-secret
      config:
        enabled: true
      sources:
        - namespace: default
          name: mongo-conf
      reload:
        enabled: true
        mode: polling
        period: 1000
#  spring:
#    sleuth:
#      sampler:
#        probability: 1.0  # Set the sampling probability to 1.0 to trace all requests
#      jaeger:
#        enabled: true
#        udp-sender:
#          host: simplest-collector  # Update with the hostname or service name of your Jaeger collector
#          port: 6831

#  sleuth:
#    enabled: false
#  jaeger:
#    enable-b3-propagation: true
#    enabled: false
#    sender-type: http
#    http-sender:
#      url: http://simplest-collector:14268/api/traces

management:
  security:
    enabled: false
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
  health:
    diskspace:
      enabled: true
  metrics:
    enable:
      process.filesystem: true
      client:
        request:
          metrics: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      minimum-expected-value:
        http.server.requests: 5ms
      maximum-expected-value:
        http.server.requests: 100ms
  httpexchanges:
    recording:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  pattern:
    level: '%prefix(%mdc{trace_id:-0}) %5p'
#          - health
#          - metrics
#          - prometheus
#          - loggers
#          - httptrace

#opentracing:
#  jaeger:
#    udp-sender:
#      host: simplest-agent.default.svc.cluster.local
#      port: 5775
#    log-spans: true
#    enabled: true
#opentracing:
#  jaeger:
#    udp-sender:
#      host: jaeger-agent.default.svc.cluster.local
#      port: 6831
#    enable-b3-propagation: true
#    enabled: true
