name: Host Deployment flow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package  # --quiet

      - name: Run tests
        run: mvn test  # --quiet

      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: matijamatovic/devops-host-backend
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag: 1.0.0
#
#      - name: Docker Login
#        env:
#          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
#          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
#        run: |
#          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
#
#      - name: Docker Build
#        run: docker-compose build
#
#      - name: Docker Tag
#        run: docker tag hotel-host-service_host-app matijamatovic/devops-host-backend:latest
#
#      - name: Docker Deploy
#        run: docker push ${{secrets.DOCKER_USERNAME}}/devops-host-backend
