name: Host Deployment flow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Docker Login
          env:
            DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
            DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          run: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

        - name: Docker Build
          run: ls ../.. && cd ../.. && docker-compose build

        - name: Docker Tag
          run: docker tag hostapp_host-app matijamatovic/devops-host-backend:latest

        - name: Docker Deploy
          run: docker push ${{secrets.DOCKER_USERNAME}}/devops-host-backend
