name: Host Deployment flow

on:
  workflow_run:
    workflows:
      - "Host App flow"
    types:
      - completed

jobs:
    deploy:
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/master'
      steps:
        - name: Docker Login
          env:
            DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
            DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          run: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

        - name: Print me
          run: echo | pwd

        - name: Docker Build
          run: docker-compose -f "compose.yaml" build

        - name: Docker Tag
          run: docker tag hostapp_host-app matijamatovic/devops-host-backend:latest

        - name: Docker Deploy
          run: docker push ${{secrets.DOCKER_USERNAME}}/devops-host-backend
